import { playfair, openSans } from './fonts';
import './globals.css';
import Navbar from '../components/Navbar2';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='sv' className={`${playfair.variable} ${openSans.variable}`}>
      <body>
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
